# Included by the top-level CMakeLists.txt.
#
# The mod password ciphertext and mask come from environment variables; they are transformed here
# at configure time and written into the build directory (never committed to the repository).
#
# Why transform them: VCMI's source code is fully open, so any material hard-coded in the source or
# present in plaintext inside the binary is effectively public. Two layers are applied here:
#   1. The material is interleaved into 4 shards character/byte by character/byte: the ciphertext
#      shards store base64 alphabet indices (not the characters themselves) and the mask shards
#      store XOR-obfuscated values -- so the binary contains neither printable ciphertext fragments
#      nor the original mask;
#   2. Each shard's XOR key is generated randomly and fixed on the first configure of this build
#      directory (secret_keys.cmake), and never ends up in the source tree.
# Recovering the original material requires understanding the reconstruction logic in
# lib/filesystem/protect/SecretConstants.cpp and then locating these keys inside the binary.
#
# The VM opcode permutation key follows the same idea: the "logical instruction -> physical byte"
# mapping is randomized once per build directory.

set(MOD_PASSWORD_ENV $ENV{MOD_PASSWORD})
if(NOT MOD_PASSWORD_ENV)
    message(FATAL_ERROR "Environment variable MOD_PASSWORD is not set, cannot configure")
endif()
if(NOT MOD_PASSWORD_ENV MATCHES "^[A-Za-z0-9+/=]+$")
    message(FATAL_ERROR "MOD_PASSWORD must be a base64 string (only A-Z a-z 0-9 + / = are allowed)")
endif()

set(MOD_PASSWORD_MASK_VALUE $ENV{MOD_PASSWORD_MASK})
if(NOT MOD_PASSWORD_MASK_VALUE)
    message(FATAL_ERROR "Environment variable MOD_PASSWORD_MASK is not set")
endif()

# Must match the table used by base64Decode in PasswordProgram.cpp
set(BASE64_ALPHABET "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")

set(SHARD_COUNT 4)

set(GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")
file(MAKE_DIRECTORY "${GENERATED_DIR}")

# ---- Per-build-directory randomized transformation keys: generated on first configure, then kept fixed ----
# The shards are transformed with these keys; if the keys were re-randomized on every configure,
# previously generated shards would no longer match.
set(SECRET_KEYS_FILE "${GENERATED_DIR}/secret_keys.cmake")
if(NOT EXISTS "${SECRET_KEYS_FILE}")
    set(GENERATED_KEY_TEXT "# Generated by cmake/ModPasswordSecrets.cmake on first configure; kept fixed afterwards.\n")
    foreach(shard RANGE 0 3)
        string(RANDOM LENGTH 2 ALPHABET "0123456789abcdef" CIPHER_KEY_BYTE)
        string(APPEND GENERATED_KEY_TEXT "set(SECRET_CIPHER_KEY_${shard} 0x${CIPHER_KEY_BYTE})\n")
    endforeach()
    foreach(shard RANGE 0 3)
        string(RANDOM LENGTH 2 ALPHABET "0123456789abcdef" MASK_KEY_BYTE)
        string(APPEND GENERATED_KEY_TEXT "set(SECRET_MASK_KEY_${shard} 0x${MASK_KEY_BYTE})\n")
    endforeach()
    file(WRITE "${SECRET_KEYS_FILE}" "${GENERATED_KEY_TEXT}")
endif()
include("${SECRET_KEYS_FILE}")

# ---- Ciphertext: interleaved character by character; each shard stores base64 alphabet indices (the padding character '=' is encoded as 64) ----
string(LENGTH "${MOD_PASSWORD_ENV}" CIPHER_LENGTH)
math(EXPR CIPHER_MAX_INDEX "${CIPHER_LENGTH} - 1")
set(CIPHER_INDEX 0)
foreach(i RANGE 0 ${CIPHER_MAX_INDEX})
    string(SUBSTRING "${MOD_PASSWORD_ENV}" ${i} 1 CIPHER_CHAR)

    string(FIND "${BASE64_ALPHABET}" "${CIPHER_CHAR}" CIPHER_VALUE)
    if(CIPHER_VALUE EQUAL -1)
        if(NOT CIPHER_CHAR STREQUAL "=")
            message(FATAL_ERROR "MOD_PASSWORD contains an invalid base64 character '${CIPHER_CHAR}'")
        endif()
        set(CIPHER_VALUE 64)
    endif()

    math(EXPR CIPHER_SHARD_INDEX "${CIPHER_INDEX} % ${SHARD_COUNT}")
    if(CIPHER_SHARD_INDEX EQUAL 0)
        math(EXPR OBFUSCATED_VALUE "${CIPHER_VALUE} ^ ${SECRET_CIPHER_KEY_0}")
    elseif(CIPHER_SHARD_INDEX EQUAL 1)
        math(EXPR OBFUSCATED_VALUE "${CIPHER_VALUE} ^ ${SECRET_CIPHER_KEY_1}")
    elseif(CIPHER_SHARD_INDEX EQUAL 2)
        math(EXPR OBFUSCATED_VALUE "${CIPHER_VALUE} ^ ${SECRET_CIPHER_KEY_2}")
    else()
        math(EXPR OBFUSCATED_VALUE "${CIPHER_VALUE} ^ ${SECRET_CIPHER_KEY_3}")
    endif()

    list(APPEND CIPHER_SHARD_${CIPHER_SHARD_INDEX} "${OBFUSCATED_VALUE}")
    math(EXPR CIPHER_INDEX "${CIPHER_INDEX} + 1")
endforeach()

# ---- Mask: a hexadecimal byte stream; after interleaving into shards, each shard is XORed with its own key ----
string(LENGTH "${MOD_PASSWORD_MASK_VALUE}" MASK_LEN)
if(MASK_LEN LESS 2)
    message(FATAL_ERROR "MOD_PASSWORD_MASK has an invalid length: ${MASK_LEN}")
endif()

math(EXPR MOD_RESULT "${MASK_LEN} % 2")
if(NOT MOD_RESULT EQUAL 0)
    message(FATAL_ERROR "MOD_PASSWORD_MASK has an invalid length: ${MASK_LEN} (must be even)")
endif()

math(EXPR MASK_MAX_INDEX "${MASK_LEN} - 2")
set(MASK_BYTE_INDEX 0)
foreach(i RANGE 0 ${MASK_MAX_INDEX} 2)
    string(SUBSTRING "${MOD_PASSWORD_MASK_VALUE}" ${i} 2 HEX_BYTE)
    string(TOUPPER "${HEX_BYTE}" HEX_BYTE)
    if(NOT HEX_BYTE MATCHES "^[0-9A-F][0-9A-F]$")
        message(FATAL_ERROR "MOD_PASSWORD_MASK contains an invalid hexadecimal byte '${HEX_BYTE}'")
    endif()

    math(EXPR MASK_SHARD_INDEX "${MASK_BYTE_INDEX} % ${SHARD_COUNT}")
    if(MASK_SHARD_INDEX EQUAL 0)
        math(EXPR OBFUSCATED_BYTE "0x${HEX_BYTE} ^ ${SECRET_MASK_KEY_0}")
    elseif(MASK_SHARD_INDEX EQUAL 1)
        math(EXPR OBFUSCATED_BYTE "0x${HEX_BYTE} ^ ${SECRET_MASK_KEY_1}")
    elseif(MASK_SHARD_INDEX EQUAL 2)
        math(EXPR OBFUSCATED_BYTE "0x${HEX_BYTE} ^ ${SECRET_MASK_KEY_2}")
    else()
        math(EXPR OBFUSCATED_BYTE "0x${HEX_BYTE} ^ ${SECRET_MASK_KEY_3}")
    endif()

    list(APPEND MASK_SHARD_${MASK_SHARD_INDEX} "${OBFUSCATED_BYTE}")
    math(EXPR MASK_BYTE_INDEX "${MASK_BYTE_INDEX} + 1")
endforeach()

# Pad empty shards with a placeholder value to avoid generating zero-length arrays (the actual read range is bounded by the length constants)
foreach(shard RANGE 0 3)
    if(NOT CIPHER_SHARD_${shard})
        list(APPEND CIPHER_SHARD_${shard} "0")
    endif()
    if(NOT MASK_SHARD_${shard})
        list(APPEND MASK_SHARD_${shard} "0")
    endif()
    string(JOIN ", " CIPHER_SHARD_${shard}_STR ${CIPHER_SHARD_${shard}})
    string(JOIN ", " MASK_SHARD_${shard}_STR ${MASK_SHARD_${shard}})
endforeach()

string(JOIN ", " CIPHER_SHARD_KEYS_STR
    ${SECRET_CIPHER_KEY_0} ${SECRET_CIPHER_KEY_1} ${SECRET_CIPHER_KEY_2} ${SECRET_CIPHER_KEY_3})
string(JOIN ", " MASK_SHARD_KEYS_STR
    ${SECRET_MASK_KEY_0} ${SECRET_MASK_KEY_1} ${SECRET_MASK_KEY_2} ${SECRET_MASK_KEY_3})

math(EXPR MASK_BYTE_COUNT "${MASK_LEN} / 2")

configure_file(
    "${CMAKE_CURRENT_LIST_DIR}/secrets.h.in"
    "${GENERATED_DIR}/secrets.h"
    @ONLY
)

# ---- VM opcode permutation key: randomly generated on first configure, then kept fixed for this build directory ----
set(VM_KEY_HEADER "${GENERATED_DIR}/vm_key.h")
if(NOT EXISTS "${VM_KEY_HEADER}")
    string(RANDOM LENGTH 2 ALPHABET "0123456789abcdef" VM_KEY_0)
    string(RANDOM LENGTH 2 ALPHABET "0123456789abcdef" VM_KEY_1)
    string(RANDOM LENGTH 2 ALPHABET "0123456789abcdef" VM_KEY_X)
    configure_file(
        "${CMAKE_CURRENT_LIST_DIR}/vm_key.h.in"
        "${VM_KEY_HEADER}"
        @ONLY
    )
endif()
