/*
 * SecretConstants.cpp, part of VCMI engine
 *
 * Authors: listed in file AUTHORS in main folder
 *
 * License: GNU General Public License v2.0 or later
 * Full text of license available in license.txt file, in main folder
 *
 */
#include "SecretConstants.h"

#include "secrets.h" // generated by CMake into the build directory, not tracked in the repository

VCMI_LIB_NAMESPACE_BEGIN

namespace ModPassword
{

namespace
{

/// The ciphertext shards store indices into this table; 64 denotes the '=' padding character
constexpr char base64Alphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/// Volatile reads, so the compiler cannot reassemble the shards into one contiguous constant in the binary
const volatile std::uint8_t * cipherShardData(std::size_t shard)
{
	switch(shard)
	{
	case 0:
		return Secrets::cipherShard0;
	case 1:
		return Secrets::cipherShard1;
	case 2:
		return Secrets::cipherShard2;
	default:
		return Secrets::cipherShard3;
	}
}

const volatile std::uint8_t * maskShardData(std::size_t shard)
{
	switch(shard)
	{
	case 0:
		return Secrets::maskShard0;
	case 1:
		return Secrets::maskShard1;
	case 2:
		return Secrets::maskShard2;
	default:
		return Secrets::maskShard3;
	}
}

}

std::string secretCipher()
{
	std::string result;
	result.resize(Secrets::cipherLength);

	for(std::size_t i = 0; i < result.size(); ++i)
	{
		const std::size_t shard = i % Secrets::cipherShardCount;
		const std::size_t offset = i / Secrets::cipherShardCount;

		const std::uint8_t value = static_cast<std::uint8_t>(
		    cipherShardData(shard)[offset] ^ Secrets::cipherShardKeys[shard]);

		result[i] = value < 64 ? base64Alphabet[value] : '=';
	}

	return result;
}

std::uint8_t secretMaskByte(std::size_t index)
{
	if(Secrets::maskLength == 0)
		return 0;

	// Matches VCMI's original reconstruction: the mask is reused cyclically by length, rather than zero-padded past its end
	const std::size_t wrapped = index % Secrets::maskLength;
	const std::size_t shard = wrapped % Secrets::maskShardCount;
	const std::size_t offset = wrapped / Secrets::maskShardCount;

	const std::uint8_t value = static_cast<std::uint8_t>(
	    maskShardData(shard)[offset] ^ Secrets::maskShardKeys[shard]);

	return value;
}

std::size_t secretMaskLength()
{
	return Secrets::maskLength;
}

}

VCMI_LIB_NAMESPACE_END
