/*
 * VmAsm.h, part of VCMI engine
 *
 * Authors: listed in file AUTHORS in main folder
 *
 * License: GNU General Public License v2.0 or later
 * Full text of license available in license.txt file, in main folder
 *
 */
#pragma once

#include "StdInc.h"

#include "vm_key.h" // generated by CMake into the build directory (one random mapping per build directory)

#include <array>
#include <cstdint>

VCMI_LIB_NAMESPACE_BEGIN

namespace ModPassword
{
namespace Vm
{

// ---------------------------------------------------------------------------
// Logical instructions
//
// What actually appears in the bytecode is the byte permuted by permuteOpcode(), not the
// values below. The permutation is a bijection (multiplication by 167 and by 23 are
// inverses modulo 256), so it can be reversed exactly.
// ---------------------------------------------------------------------------
enum LogicalOp : std::uint8_t
{
	opEnd = 0,
	opPush8,          // imm8   push immediate
	opPush32,         // imm32
	opLoadLocal,      // imm8   push local variable
	opStoreLocal,     // imm8   pop and write local variable
	opDup,            // duplicate top of stack
	opPop,            // discard top of stack
	opAdd,
	opSub,
	opXor,
	opAnd,
	opMul,
	opLessThan,       // a < b ? 1 : 0
	opEqual,          // a == b ? 1 : 0
	opNotEqual,       // a != b ? 1 : 0
	opJump,           // int16  offset relative to the next instruction
	opJumpIfZero,     // int16  pop condition, jump if zero
	opJumpIfNotZero,  // int16  pop condition, jump if non-zero
	opCallHost,       // imm8   call host function, push result
	opLoadBuffer8,    // imm8 bufferId: pop index, push that byte
	opStoreBuffer8,   // imm8 bufferId: pop value, then pop index, and store
	opBufferLength,   // imm8 bufferId: push length
	opReturn,         // pop return value and finish
	opCount
};

/// Logical instruction -> physical byte
constexpr std::uint8_t permuteOpcode(std::uint8_t logical)
{
	return static_cast<std::uint8_t>(
	    ((static_cast<std::uint8_t>(logical ^ vmOpcodeKey0) * 167u + vmOpcodeKey1) ^ vmOpcodeXorMask));
}

/// Physical byte -> logical instruction (167 * 23 == 1 mod 256)
constexpr std::uint8_t restoreOpcode(std::uint8_t physical)
{
	return static_cast<std::uint8_t>(
	    ((static_cast<std::uint8_t>(physical ^ vmOpcodeXorMask) - vmOpcodeKey1) * 23u) ^ vmOpcodeKey0);
}

constexpr int maxProgramBytes = 512;
constexpr int maxLabels = 16;

struct Program
{
	std::array<std::uint8_t, maxProgramBytes> bytes{};
	int size = 0;
};

// ---------------------------------------------------------------------------
// Minimal assembler
//
// Usage: emit instructions in order inside a constexpr function, with label ids used as
// jump targets first and finish() backfilling them all. Because the whole process runs at
// compile time, only the bytecode ends up in the output, not the assembly process itself.
// ---------------------------------------------------------------------------
struct Assembler
{
	Program program{};
	std::array<int, maxLabels> labelOffsets{};
	std::array<int, maxLabels> patchOffsets{};
	std::array<int, maxLabels> patchLabels{};
	int patchCount = 0;

	constexpr void byte(std::uint8_t value)
	{
		program.bytes[static_cast<size_t>(program.size)] = value;
		++program.size;
	}

	constexpr void op(LogicalOp logical)
	{
		byte(permuteOpcode(static_cast<std::uint8_t>(logical)));
	}

	constexpr void imm8(std::uint8_t value)
	{
		byte(value);
	}

	constexpr void imm32(std::uint32_t value)
	{
		byte(static_cast<std::uint8_t>(value & 0xffu));
		byte(static_cast<std::uint8_t>((value >> 8) & 0xffu));
		byte(static_cast<std::uint8_t>((value >> 16) & 0xffu));
		byte(static_cast<std::uint8_t>((value >> 24) & 0xffu));
	}

	/// Define a jump label
	constexpr void label(int id)
	{
		labelOffsets[static_cast<size_t>(id)] = program.size;
	}

	/// Instruction with a jump; the target label may be defined later
	constexpr void jump(LogicalOp logical, int id)
	{
		op(logical);
		patchOffsets[static_cast<size_t>(patchCount)] = program.size;
		patchLabels[static_cast<size_t>(patchCount)] = id;
		++patchCount;
		byte(0);
		byte(0);
	}

	constexpr Program finish()
	{
		for(int i = 0; i < patchCount; ++i)
		{
			const int target = labelOffsets[static_cast<size_t>(patchLabels[static_cast<size_t>(i)])];
			const int offset = target - (patchOffsets[static_cast<size_t>(i)] + 2);
			program.bytes[static_cast<size_t>(patchOffsets[static_cast<size_t>(i)])] =
			    static_cast<std::uint8_t>(offset & 0xff);
			program.bytes[static_cast<size_t>(patchOffsets[static_cast<size_t>(i)] + 1)] =
			    static_cast<std::uint8_t>((offset >> 8) & 0xff);
		}
		return program;
	}
};

}
}

VCMI_LIB_NAMESPACE_END
